config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'mangas#index'

  resources :mangas do
    resources :manga_reviews, only: [:create, :update, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :chapters do
      resources :chapter_reviews, only: [:create, :update, :destroy]
    end
    #get top manga ranking
    collection do
      get :top
    end
  end

  get "dashboard", to: "pages#dashboard"
  resources :bookmarks, only: [:destroy]
end

app/views/pages/dashboard.html.erb
<div class="container">
  <%# user avatar name and social media %>
  <%= link_to "Edit Profile", edit_user_registration_path(current_user) %>
  <div class="border border-primary d-flex align-items-center">
    <div><%= image_tag "https://kitt.lewagon.com/placeholder/users/mchancfy", class: "border border-primary avatar"%></div>
    <div class="border border-primary">
      <h1><%= current_user.username %></h1>

      <i class="fa-solid fa-envelope"></i>

      <% if current_user.twitter.present? %>
        <i class="fa-brands fa-twitter"></i>
      <% end %>

      <% if current_user.instagram.present? %>
        <i class="fa-brands fa-instagram"></i>
      <% end %>
    </div>
  </div>

  <%# user bio %>
  <div class="border border-primary">
  <p>Bio: <%= current_user.bio %></p>
  </div>

  <%# bookmark title%>
  <div class="border border-primary d-flex justify-content-between align-items-end">
    <h3>Bookmarked<i class="fa-solid fa-heart" style="color: #f39bd3;"></i></h3>
    <h4>See all -></h4>
  </div>

  <hr>
  <%# display user's bookmark %>
  <div>
    <% if !@bookmarks.nil? %>
      <% @bookmarks.each do |bookmark| %>
        <%= bookmark.manga.manga_title %>
        <!-- display other manga details here -->
      <% end %>
    <% else %>
      <p>Start watching manga and bookmark them!</p>
    <% end %>
  </div>

  <%# do each @bookmark.all.manga_id.manga_title cover%>

  <%# My Manga title + manga_new_path %>
  <div class="border border-primary d-flex justify-content-between align-items-end">
    <h3>My Manga
    <%= link_to new_manga_path do %>
      <i class="fa-solid fa-arrow-up-from-bracket"></i>
    <% end %>
    </h3>
    <h4>See all -></h4>
  </div>
  <hr>
  <%# do each @ %>


  <%# display user's manga %>
  <div>
    <ul></ul>
    <% if !@mangas.nil? %>
      <% @mangas.each do |manga| %>
        <li><%= manga.manga_title %></li>
        <!-- display other manga details here -->
      <% end %>
    <% else %>
      <p>We can't wait to see your manga!</p>
    <% end %>
    </ul>
  </div>
</div>

<%= link_to "Hot Manga of this week", top_mangas_path %>
<hr>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>